# Generated by Django 3.2.8 on 2021-10-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='including',
            name='foodnum',
            field=models.IntegerField(blank=True, db_column='foodNum', null=True),
        ),
    ]
