# Generated by Django 3.2.8 on 2021-11-01 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canteenApp', '0002_including_foodnum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vieworderfood',
            fields=[
                ('foodid', models.OneToOneField(db_column='foodId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='canteenApp.food')),
                ('foodnum', models.IntegerField(blank=True, db_column='foodNum', null=True)),
                ('foodname', models.TextField(db_column='foodName')),
                ('foodprice', models.IntegerField(db_column='foodPrice')),
                ('foodcate', models.TextField(db_column='foodCate')),
                ('orderid', models.ForeignKey(db_column='orderId', on_delete=django.db.models.deletion.DO_NOTHING, to='canteenApp.orderlist')),
            ],
            options={
                'db_table': 'vieworderfood',
            },
        ),
    ]
