# Generated by Django 3.2.8 on 2021-11-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenApp', '0003_vieworderfood'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewordergood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.TextField(db_column='foodName')),
                ('foodmoney', models.IntegerField(db_column='foodMoney')),
            ],
            options={
                'db_table': 'viewfoodsold',
            },
        ),
        migrations.AddField(
            model_name='adding',
            name='goodnum',
            field=models.IntegerField(blank=True, db_column='goodNum', null=True),
        ),
    ]
